# Generated by Django 3.2.25 on 2024-06-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='friendy_name',
            new_name='friendly_name',
        ),
    ]
